export { default as About } from './About/About';
export { default as Admin } from './Admin/Admin';
export { default as Students } from './Admin/Students/Students';
export { default as Courses } from './Courses/Courses';
export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Detail } from './Detail/Detail';
export { default as BuyButtonComponent } from './Donate/BuyButtonComponent';
export { default as Donate } from './Donate/Donate';
export { default as Gracias } from './Gracias/Gracias';
export { default as Student } from './Student/Student';
export { default as ActiveCourse } from './Teacher/ActiveCourse/ActiveCourse';
export { default as ActiveCourses } from './Teacher/ActiveCourses/ActiveCourses';
export { default as Create } from './Teacher/Create/Create';
export { default as DeleteCourse } from './Teacher/DeleteCourse/DeleteCourse';
export { default as DeletedCourses } from './Teacher/DeletedCourses/DeletedCourses';
export { default as TeacherCourses } from './Teacher/TeacherCourses/TeacherCourses';
export * from './Teacher';
export { default as Home } from './home/Home';
